# -- DEV DOCKER-COMPOSE --
# -- DO NOT USE IN PRODUCTION! --

version: "3"
services:
  db:
    image: postgis/postgis:14-3.2-alpine
    environment:
      POSTGRES_DB: mendel
      POSTGRES_PASSWORD: mendel
      POSTGRES_USER: mendel
    container_name: db
    ports:
      - 5432:5432
    networks:
      - mendelnet

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: dummy@dummy.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    networks:
      - mendelnet
    ports:
      - "3001:80"
    depends_on:
      - db
  app:
    build:
      context: ../
      dockerfile: dev/Dockerfile
    depends_on:
      - db
    networks:
      - mendelnet
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ..:/mendel
      - ~/.gitconfig:/etc/gitconfig

networks:
  mendelnet:
