# -- DEV DOCKER-COMPOSE --
# -- DO NOT USE IN PRODUCTION! --

version: "3"
services:
  db:
    image: postgis/postgis:14-3.2-alpine
    environment:
      POSTGRES_DB: mendel
      POSTGRES_PASSWORD: mendel
      POSTGRES_USER: mendel
    container_name: db
    networks:
      - mendelnet

  adminer:
    image: adminer:latest
    networks:
      - mendelnet
    ports:
      - "3001:8080"
    depends_on:
      - db
  app:
    build:
      context: ../
      dockerfile: dev/Dockerfile
    depends_on:
      - db
    networks:
      - mendelnet
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ..:/mendel
      - ~/.gitconfig:/etc/gitconfig

networks:
  mendelnet:
