version: "3"
services:
  db:
    image: postgis/postgis:14-3.2-alpine
    environment:
      POSTGRES_DB: mendel
      POSTGRES_PASSWORD: mendel
      POSTGRES_USER: mendel
    container_name: db
    networks:
      - mendelnet

  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    networks:
      - mendelnet
    ports:
      - "8080:8080"

networks:
  mendelnet:
