version: "3"
services:
  db:
    image: ghcr.io/baosystems/postgis:14-3.2
    environment:
      POSTGRES_DB: mendel
      POSTGRES_PASSWORD: mendel
      POSTGRES_USER: mendel
    container_name: mendel-db

  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    ports:
      - "2468:3000"
